CREATE TABLE distanualb
(
id SERIAL,
codPonto int,
datPonto date,
codPonto1 int,
distBruta1 float[],
distTratada1 float[],
datPonto1 date,
codPonto2 int,
distBruta2 float[],
distTratada2 float[],
datPonto2 date,
codPonto3 int,
distBruta3 float[],
distTratada3 float[],
datPonto3 date,
codPonto4 int,
distBruta4 float[],
distTratada4 float[],
datPonto4 date,
codPonto5 int,
distBruta5 float[],
distTratada5 float[],
datPonto5 date,
codPonto6 int,
distBruta6 float[],
distTratada6 float[],
datPonto6 date,
CONSTRAINT keyDistanualb PRIMARY KEY (id),
CONSTRAINT estpontob FOREIGN KEY (codPonto) REFERENCES ponto,
CONSTRAINT estpontob1 FOREIGN KEY (codPonto1) REFERENCES ponto,
CONSTRAINT estpontob2 FOREIGN KEY (codPonto2) REFERENCES ponto,
CONSTRAINT estpontob3 FOREIGN KEY (codPonto3) REFERENCES ponto,
CONSTRAINT estpontob4 FOREIGN KEY (codPonto4) REFERENCES ponto,
CONSTRAINT estpontob5 FOREIGN KEY (codPonto5) REFERENCES ponto,
CONSTRAINT estpontob6 FOREIGN KEY (codPonto6) REFERENCES ponto
);
