CREATE TABLE disttotalw
(
id SERIAL,
codPonto int,
codPonto1 int,
distBruta1 float[],
distTratada1 float[],
codPonto2 int,
distBruta2 float[],
distTratada2 float[],
codPonto3 int,
distBruta3 float[],
distTratada3 float[],
codPonto4 int,
distBruta4 float[],
distTratada4 float[],
codPonto5 int,
distBruta5 float[],
distTratada5 float[],
codPonto6 int,
distBruta6 float[],
distTratada6 float[],
CONSTRAINT keyDistTotalw PRIMARY KEY (id),
CONSTRAINT estwpontototal FOREIGN KEY (codPonto) REFERENCES ponto,
CONSTRAINT estwpontototal1 FOREIGN KEY (codPonto1) REFERENCES ponto,
CONSTRAINT estwpontototal2 FOREIGN KEY (codPonto2) REFERENCES ponto,
CONSTRAINT estwpontototal3 FOREIGN KEY (codPonto3) REFERENCES ponto,
CONSTRAINT estwpontototal4 FOREIGN KEY (codPonto4) REFERENCES ponto,
CONSTRAINT estwpontototal5 FOREIGN KEY (codPonto5) REFERENCES ponto,
CONSTRAINT estwpontototal6 FOREIGN KEY (codPonto6) REFERENCES ponto
);
