CREATE TABLE disttotalb
(
id SERIAL,
codPonto int,
codPonto1 int,
distBruta1 float[],
distTratada1 float[],
codPonto2 int,
distBruta2 float[],
distTratada2 float[],
codPonto3 int,
distBruta3 float[],
distTratada3 float[],
codPonto4 int,
distBruta4 float[],
distTratada4 float[],
codPonto5 int,
distBruta5 float[],
distTratada5 float[],
codPonto6 int,
distBruta6 float[],
distTratada6 float[],
CONSTRAINT keyDistTotalb PRIMARY KEY (id),
CONSTRAINT estbpontototal FOREIGN KEY (codPonto) REFERENCES ponto,
CONSTRAINT estbpontototal1 FOREIGN KEY (codPonto1) REFERENCES ponto,
CONSTRAINT estbpontototal2 FOREIGN KEY (codPonto2) REFERENCES ponto,
CONSTRAINT estbpontototal3 FOREIGN KEY (codPonto3) REFERENCES ponto,
CONSTRAINT estbpontototal4 FOREIGN KEY (codPonto4) REFERENCES ponto,
CONSTRAINT estbpontototal5 FOREIGN KEY (codPonto5) REFERENCES ponto,
CONSTRAINT estbpontototal6 FOREIGN KEY (codPonto6) REFERENCES ponto
);
